services:
  
  webapp_diary_local:
    image: webapp_diary_local:1.0.0
    container_name: webapp_diary_local
    build:
      context: .
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis
    networks:
      - network_diary_local
  
  mysql:
    image: mysql:8.0.32
    container_name: mysql_diary_local
    restart: always
    env_file:
      - ./src/.env
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_TCP_PORT: 3306
    volumes:
      - mysql_diary_local_data:/var/lib/mysql
    networks:
      - network_diary_local

  smtp:
    platform: linux/x86_64
    image: mailhog/mailhog
    container_name: smtp_diary_local
    logging:
      driver: 'none'
    ports:
      - 8003:1025
      - 8100:8025
    networks:
      - network_diary_local

  redis:
    image: redis:7.0.5-alpine
    hostname: redis
    networks:
      - network_diary_local


networks:
  network_diary_local:

volumes:
  mysql_diary_local_data:
